/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.nemocnica;

import javax.swing.JOptionPane;

/**
 *
 * @author szoplakz
 */
public class DatabazaForm extends javax.swing.JDialog {

    /**
     * Creates new form DatabazaForm
     */
    public DatabazaForm(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DiagnozyList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        LiekList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        LiecbaList = new javax.swing.JList<>();
        PridajDiagnozuButton = new javax.swing.JButton();
        UpravDiagnozuButton = new javax.swing.JButton();
        PridajLiekButton = new javax.swing.JButton();
        UpravLiekButton = new javax.swing.JButton();
        PridajLiecbuButton = new javax.swing.JButton();
        UpravLiecbuButton = new javax.swing.JButton();
        LiecbyLabel = new javax.swing.JLabel();
        DiagnozyLabel1 = new javax.swing.JLabel();
        LiekyLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        DiagnozyList.setModel(new DiagnozaListModel());
        jScrollPane1.setViewportView(DiagnozyList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 33, 147, 320);

        LiekList.setModel(new LiekListModel());
        jScrollPane2.setViewportView(LiekList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(200, 33, 144, 320);

        LiecbaList.setModel(new LiecbaListModel());
        jScrollPane3.setViewportView(LiecbaList);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(369, 33, 160, 320);

        PridajDiagnozuButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PridajDiagnozuButton.setForeground(new java.awt.Color(0, 102, 0));
        PridajDiagnozuButton.setText("Pridaj");
        PridajDiagnozuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajDiagnozuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PridajDiagnozuButton);
        PridajDiagnozuButton.setBounds(10, 360, 140, 47);

        UpravDiagnozuButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        UpravDiagnozuButton.setForeground(new java.awt.Color(0, 102, 0));
        UpravDiagnozuButton.setText("Uprav");
        UpravDiagnozuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravDiagnozuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpravDiagnozuButton);
        UpravDiagnozuButton.setBounds(10, 410, 140, 47);

        PridajLiekButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PridajLiekButton.setForeground(new java.awt.Color(0, 102, 0));
        PridajLiekButton.setText("Pridaj");
        PridajLiekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajLiekButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PridajLiekButton);
        PridajLiekButton.setBounds(200, 360, 130, 47);

        UpravLiekButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        UpravLiekButton.setForeground(new java.awt.Color(0, 102, 0));
        UpravLiekButton.setText("Uprav");
        UpravLiekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravLiekButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpravLiekButton);
        UpravLiekButton.setBounds(200, 410, 130, 47);

        PridajLiecbuButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PridajLiecbuButton.setForeground(new java.awt.Color(0, 102, 0));
        PridajLiecbuButton.setText("Pridaj");
        PridajLiecbuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajLiecbuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PridajLiecbuButton);
        PridajLiecbuButton.setBounds(370, 360, 160, 47);

        UpravLiecbuButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        UpravLiecbuButton.setForeground(new java.awt.Color(0, 102, 0));
        UpravLiecbuButton.setText("Uprav");
        UpravLiecbuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravLiecbuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpravLiecbuButton);
        UpravLiecbuButton.setBounds(370, 410, 160, 47);

        LiecbyLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        LiecbyLabel.setForeground(new java.awt.Color(0, 102, 0));
        LiecbyLabel.setText("Liecby:");
        getContentPane().add(LiecbyLabel);
        LiecbyLabel.setBounds(370, 10, 80, 20);

        DiagnozyLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        DiagnozyLabel1.setForeground(new java.awt.Color(0, 102, 0));
        DiagnozyLabel1.setText("Diagnozy:");
        getContentPane().add(DiagnozyLabel1);
        DiagnozyLabel1.setBounds(10, 10, 80, 20);

        LiekyLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        LiekyLabel.setForeground(new java.awt.Color(0, 102, 0));
        LiekyLabel.setText("Lieky:");
        getContentPane().add(LiekyLabel);
        LiekyLabel.setBounds(200, 10, 80, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PridajDiagnozuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajDiagnozuButtonActionPerformed
     
        PridajUpravDatabazuForm form = new PridajUpravDatabazuForm(this,true,false,"diagnoza",null,null,null);
             form.setVisible(true);
    }//GEN-LAST:event_PridajDiagnozuButtonActionPerformed

    private void UpravDiagnozuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravDiagnozuButtonActionPerformed
          if(DiagnozyList.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Je potrebné najskôr označiť diagnozu.");
        } else {
            // vybratie zaznamu v tabulke
            int index = DiagnozyList.getSelectedIndex();
            Diagnoza diagnoza = ((DiagnozaListModel) DiagnozyList.getModel()).getElementAt(index);
             PridajUpravDatabazuForm form = new PridajUpravDatabazuForm(this,true,true,"diagnoza",diagnoza,null,null);
             form.setVisible(true);
          }
    }//GEN-LAST:event_UpravDiagnozuButtonActionPerformed

    private void PridajLiekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajLiekButtonActionPerformed
         PridajUpravDatabazuForm form = new PridajUpravDatabazuForm(this,true,false,"liek",null,null,null);
             form.setVisible(true);
    }//GEN-LAST:event_PridajLiekButtonActionPerformed

    private void UpravLiekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravLiekButtonActionPerformed
        if(LiekList.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Je potrebné najskôr označiť liek.");
        } else {
            // vybratie zaznamu v tabulke
            int index = LiekList.getSelectedIndex();
            Liek liek = ((LiekListModel) LiekList.getModel()).getElementAt(index);
             PridajUpravDatabazuForm form = new PridajUpravDatabazuForm(this,true,true,"liek",null,liek,null);
             form.setVisible(true);
          }
    }//GEN-LAST:event_UpravLiekButtonActionPerformed

    private void PridajLiecbuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajLiecbuButtonActionPerformed
         PridajUpravDatabazuForm form = new PridajUpravDatabazuForm(this,true,false,"liecba",null,null,null);
             form.setVisible(true);
    }//GEN-LAST:event_PridajLiecbuButtonActionPerformed

    private void UpravLiecbuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravLiecbuButtonActionPerformed
       if(LiecbaList.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Je potrebné najskôr označiť liecbu.");
        } else {
            // vybratie zaznamu v tabulke
            int index = LiecbaList.getSelectedIndex();
           Liecba liecba = ((LiecbaListModel) LiecbaList.getModel()).getElementAt(index);
             PridajUpravDatabazuForm form = new PridajUpravDatabazuForm(this,true,true,"liecba",null,null,liecba);
             form.setVisible(true);
          }
    }//GEN-LAST:event_UpravLiecbuButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiagnozyLabel1;
    private javax.swing.JList<Diagnoza> DiagnozyList;
    private javax.swing.JList<Liecba> LiecbaList;
    private javax.swing.JLabel LiecbyLabel;
    private javax.swing.JList<Liek> LiekList;
    private javax.swing.JLabel LiekyLabel;
    private javax.swing.JButton PridajDiagnozuButton;
    private javax.swing.JButton PridajLiecbuButton;
    private javax.swing.JButton PridajLiekButton;
    private javax.swing.JButton UpravDiagnozuButton;
    private javax.swing.JButton UpravLiecbuButton;
    private javax.swing.JButton UpravLiekButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
