/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.nemocnica;

/**
 *
 * @author szoplakz
 */
public class EditUserForm extends javax.swing.JDialog {

    /**
     * Creates new form EditProfile
     */
    private Pouzivatel pouzivatel;
     private PouzivatelDAO pouzivatelDao = DaoFactory.INSTANCE.getPouzivatelDao();
            
    public EditUserForm(java.awt.Dialog parent, boolean modal, Pouzivatel pouzivatel) {
        super(parent, modal);
        initComponents();
        this.setSize(340, 200);
        this.pouzivatel=pouzivatel;
        prihlasovacieMenoTextField.setText(pouzivatel.getLogin());
        prihlasovacieHesloTextField.setText(pouzivatel.getPassword());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prihlasovacieMenoTextField = new javax.swing.JTextField();
        prihlasovacieMenoLabel = new javax.swing.JLabel();
        prihlasovacieHesloLabel = new javax.swing.JLabel();
        prihlasovacieHesloTextField = new javax.swing.JPasswordField();
        ZmenitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        prihlasovacieMenoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prihlasovacieMenoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(prihlasovacieMenoTextField);
        prihlasovacieMenoTextField.setBounds(90, 20, 220, 32);

        prihlasovacieMenoLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        prihlasovacieMenoLabel.setForeground(new java.awt.Color(0, 102, 0));
        prihlasovacieMenoLabel.setText("Meno:");
        getContentPane().add(prihlasovacieMenoLabel);
        prihlasovacieMenoLabel.setBounds(30, 20, 50, 30);

        prihlasovacieHesloLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        prihlasovacieHesloLabel.setForeground(new java.awt.Color(0, 102, 0));
        prihlasovacieHesloLabel.setText("Heslo:");
        getContentPane().add(prihlasovacieHesloLabel);
        prihlasovacieHesloLabel.setBounds(30, 60, 60, 26);

        prihlasovacieHesloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prihlasovacieHesloTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(prihlasovacieHesloTextField);
        prihlasovacieHesloTextField.setBounds(90, 60, 220, 34);

        ZmenitButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ZmenitButton.setForeground(new java.awt.Color(0, 102, 0));
        ZmenitButton.setText("Zmeniť");
        ZmenitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZmenitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ZmenitButton);
        ZmenitButton.setBounds(70, 120, 189, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 340, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prihlasovacieMenoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prihlasovacieMenoTextFieldActionPerformed

    }//GEN-LAST:event_prihlasovacieMenoTextFieldActionPerformed

    private void prihlasovacieHesloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prihlasovacieHesloTextFieldActionPerformed

    }//GEN-LAST:event_prihlasovacieHesloTextFieldActionPerformed

    private void ZmenitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZmenitButtonActionPerformed
        pouzivatel.setLogin(prihlasovacieMenoTextField.getText());
        pouzivatel.setPassword(prihlasovacieHesloTextField.getText());
        pouzivatelDao.upravPouzivatela(pouzivatel);
        pouzivatelDao.zmenHeslo(pouzivatel);
    }//GEN-LAST:event_ZmenitButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ZmenitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel prihlasovacieHesloLabel;
    private javax.swing.JTextField prihlasovacieHesloTextField;
    private javax.swing.JLabel prihlasovacieMenoLabel;
    private javax.swing.JTextField prihlasovacieMenoTextField;
    // End of variables declaration//GEN-END:variables
}
