/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.nemocnica;

import javax.swing.JOptionPane;

/**
 *
 * @author szoplakz
 */
public class PacientForm extends javax.swing.JDialog {

    /**
     * Creates new form LekarForm
     */
    public PacientForm(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PacientTable = new javax.swing.JTable();
        MenoLabel = new javax.swing.JLabel();
        PriezviskoLabel = new javax.swing.JLabel();
        VekLabel = new javax.swing.JLabel();
        ZobrazButton = new javax.swing.JButton();
        PridajButton = new javax.swing.JButton();
        UpravButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        PacientTable.setModel(new PacientTableModel());
        jScrollPane1.setViewportView(PacientTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 452, 310);

        MenoLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        MenoLabel.setForeground(new java.awt.Color(0, 102, 0));
        MenoLabel.setText("Meno:");
        getContentPane().add(MenoLabel);
        MenoLabel.setBounds(470, 190, 272, 28);

        PriezviskoLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PriezviskoLabel.setForeground(new java.awt.Color(0, 102, 0));
        PriezviskoLabel.setText("Priezvisko:");
        getContentPane().add(PriezviskoLabel);
        PriezviskoLabel.setBounds(470, 240, 272, 28);

        VekLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        VekLabel.setForeground(new java.awt.Color(0, 102, 0));
        VekLabel.setText("Vek:");
        getContentPane().add(VekLabel);
        VekLabel.setBounds(470, 290, 272, 28);

        ZobrazButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ZobrazButton.setForeground(new java.awt.Color(0, 102, 0));
        ZobrazButton.setText("Zobraz");
        ZobrazButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZobrazButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ZobrazButton);
        ZobrazButton.setBounds(468, 11, 100, 46);

        PridajButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PridajButton.setForeground(new java.awt.Color(0, 102, 0));
        PridajButton.setText("Pridaj");
        PridajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PridajButton);
        PridajButton.setBounds(468, 63, 100, 47);

        UpravButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        UpravButton.setForeground(new java.awt.Color(0, 102, 0));
        UpravButton.setText("Uprav");
        UpravButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpravButton);
        UpravButton.setBounds(470, 130, 100, 47);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZobrazButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZobrazButtonActionPerformed
        if(PacientTable.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Je potrebné najskôr označiť lekára.");
        } else {
            // vybratie zaznamu v tabulke
            int riadok = PacientTable.getSelectedRow();
            Pacient pacient = ((PacientTableModel) PacientTable.getModel()).getPacientAt(riadok);
            MenoLabel.setText("Meno: " + pacient.getMeno());
            PriezviskoLabel.setText("Priezvisko: " + pacient.getPriezvisko());
            VekLabel.setText("Specializacia: " + pacient.getVek());
    }//GEN-LAST:event_ZobrazButtonActionPerformed
    }
    
    private void PridajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajButtonActionPerformed
       PridajUpravPacientaForm pridatForm = new PridajUpravPacientaForm(this,true,false,null);
        pridatForm.setVisible(true);
    }//GEN-LAST:event_PridajButtonActionPerformed

    private void UpravButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravButtonActionPerformed
       if(PacientTable.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Je potrebné najskôr označiť lekára.");
        } else {
            // vybratie zaznamu v tabulke
            int riadok = PacientTable.getSelectedRow();
            Lekar lekar = ((LekariTableModel) PacientTable.getModel()).getLekarAt(riadok);
        
        PridajUpravLekaraForm pridatForm = new PridajUpravLekaraForm(this,true,true,lekar);
        pridatForm.setVisible(true); 
        } 
    }//GEN-LAST:event_UpravButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenoLabel;
    private javax.swing.JTable PacientTable;
    private javax.swing.JButton PridajButton;
    private javax.swing.JLabel PriezviskoLabel;
    private javax.swing.JButton UpravButton;
    private javax.swing.JLabel VekLabel;
    private javax.swing.JButton ZobrazButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
