package sk.upjs.ics.paz1c.nemocnica;

import java.awt.Dialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author szoplakz
 */
public class PridajUpravLekaraForm extends javax.swing.JDialog {

    /**
     * Creates new form PridajUpravLekara
     */
    
    private Lekar lekar;
    private Boolean uprav;
    LekarDAO lekarDao = DaoFactory.INSTANCE.getLekarDao();
    public PridajUpravLekaraForm(java.awt.Dialog parent, boolean modal, boolean uprav, Lekar lekar) {
        super(parent, modal);
        initComponents();
        this.setSize(540, 230);
        this.uprav = uprav;
        
         if(uprav){
         this.lekar=lekar;    
         MenoTextField.setText(lekar.getMeno());
         PriezviskoTextField.setText(lekar.getPriezvisko());
         SpecializaciaTextField.setText(lekar.getSpecializacia());
         PridajUpravButton.setText("Uprav");
         } else {
         PridajUpravButton.setText("Pridaj");
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MenoLabel = new javax.swing.JLabel();
        PriezviskoLabel = new javax.swing.JLabel();
        SpecializaciaLabel = new javax.swing.JLabel();
        SpecializaciaTextField = new javax.swing.JTextField();
        MenoTextField = new javax.swing.JTextField();
        PriezviskoTextField = new javax.swing.JTextField();
        PridajUpravButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        MenoLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        MenoLabel.setForeground(new java.awt.Color(0, 102, 0));
        MenoLabel.setText("Meno:");
        getContentPane().add(MenoLabel);
        MenoLabel.setBounds(0, 10, 100, 28);

        PriezviskoLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PriezviskoLabel.setForeground(new java.awt.Color(0, 102, 0));
        PriezviskoLabel.setText("Priezvisko:");
        getContentPane().add(PriezviskoLabel);
        PriezviskoLabel.setBounds(0, 60, 110, 28);

        SpecializaciaLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        SpecializaciaLabel.setForeground(new java.awt.Color(0, 102, 0));
        SpecializaciaLabel.setText("Specializacia:");
        getContentPane().add(SpecializaciaLabel);
        SpecializaciaLabel.setBounds(0, 110, 110, 28);
        getContentPane().add(SpecializaciaTextField);
        SpecializaciaTextField.setBounds(115, 105, 379, 33);
        getContentPane().add(MenoTextField);
        MenoTextField.setBounds(115, 11, 379, 33);
        getContentPane().add(PriezviskoTextField);
        PriezviskoTextField.setBounds(115, 55, 379, 33);

        PridajUpravButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PridajUpravButton.setForeground(new java.awt.Color(0, 102, 0));
        PridajUpravButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridajUpravButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PridajUpravButton);
        PridajUpravButton.setBounds(190, 160, 100, 43);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 540, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PridajUpravButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridajUpravButtonActionPerformed
        if(uprav){
          lekar.setMeno(MenoTextField.getText());
          lekar.setPriezvisko(PriezviskoTextField.getText());
          lekar.setSpecializacia(SpecializaciaTextField.getText());
          lekarDao.upravLekara(lekar);
        } else {
            lekar = new Lekar();
             lekar.setMeno(MenoTextField.getText());
          lekar.setPriezvisko(PriezviskoTextField.getText());
          lekar.setSpecializacia(SpecializaciaTextField.getText());
          lekarDao.pridajLekara(lekar);
        }
            LekarForm lekarform = new LekarForm((Dialog) this.getParent().getParent(),true);
            this.getParent().setVisible(false);
            lekarform.setVisible(true);
            this.setVisible(false);
            
    }//GEN-LAST:event_PridajUpravButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenoLabel;
    private javax.swing.JTextField MenoTextField;
    private javax.swing.JButton PridajUpravButton;
    private javax.swing.JLabel PriezviskoLabel;
    private javax.swing.JTextField PriezviskoTextField;
    private javax.swing.JLabel SpecializaciaLabel;
    private javax.swing.JTextField SpecializaciaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
