/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.nemocnica;

/**
 *
 * @author szoplakz
 */
public class ProfilForm extends javax.swing.JDialog {

    /**
     * Creates new form ProfileForm
     */
    
    private Pouzivatel pouzivatel; 
    
    public ProfilForm(java.awt.Frame parent, boolean modal, Pouzivatel pouzivatel) {
        super(parent, modal);
        initComponents();
        this.pouzivatel=pouzivatel;
        this.setSize(570,340);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OdhalsitButton = new javax.swing.JButton();
        UpravitButton1 = new javax.swing.JButton();
        ZaznamyButton = new javax.swing.JButton();
        ZaznamyLabel = new javax.swing.JLabel();
        LekáriLabel = new javax.swing.JLabel();
        LekáriButton = new javax.swing.JButton();
        PacientiLabel = new javax.swing.JLabel();
        PacientiButton = new javax.swing.JButton();
        DatabazaLabel = new javax.swing.JLabel();
        DatabazaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        OdhalsitButton.setForeground(new java.awt.Color(0, 102, 0));
        OdhalsitButton.setText("Odhlásiť sa");
        OdhalsitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdhalsitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OdhalsitButton);
        OdhalsitButton.setBounds(420, 70, 110, 40);

        UpravitButton1.setForeground(new java.awt.Color(0, 102, 0));
        UpravitButton1.setText("Upraviť Profil");
        UpravitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravitButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(UpravitButton1);
        UpravitButton1.setBounds(420, 20, 110, 40);

        ZaznamyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DiagnosisIcon.png"))); // NOI18N
        ZaznamyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZaznamyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ZaznamyButton);
        ZaznamyButton.setBounds(30, 240, 80, 70);

        ZaznamyLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ZaznamyLabel.setForeground(new java.awt.Color(0, 102, 0));
        ZaznamyLabel.setText("Záznamy");
        getContentPane().add(ZaznamyLabel);
        ZaznamyLabel.setBounds(30, 220, 110, 20);

        LekáriLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        LekáriLabel.setForeground(new java.awt.Color(0, 102, 0));
        LekáriLabel.setText("Lekári");
        getContentPane().add(LekáriLabel);
        LekáriLabel.setBounds(160, 220, 110, 20);

        LekáriButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoctorIcon.png"))); // NOI18N
        LekáriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LekáriButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LekáriButton);
        LekáriButton.setBounds(160, 240, 80, 70);

        PacientiLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PacientiLabel.setForeground(new java.awt.Color(0, 102, 0));
        PacientiLabel.setText("Pacienti");
        getContentPane().add(PacientiLabel);
        PacientiLabel.setBounds(300, 220, 110, 20);

        PacientiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PatientIcon.png"))); // NOI18N
        PacientiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacientiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PacientiButton);
        PacientiButton.setBounds(300, 240, 80, 70);

        DatabazaLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        DatabazaLabel.setForeground(new java.awt.Color(0, 102, 0));
        DatabazaLabel.setText("Databáza");
        getContentPane().add(DatabazaLabel);
        DatabazaLabel.setBounds(430, 220, 110, 20);

        DatabazaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PillIcon.png"))); // NOI18N
        DatabazaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabazaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DatabazaButton);
        DatabazaButton.setBounds(430, 240, 80, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OdhalsitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdhalsitButtonActionPerformed
        PrvyForm prvyForm = new PrvyForm();
            prvyForm.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_OdhalsitButtonActionPerformed

    private void UpravitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravitButton1ActionPerformed
       EditForm editForm = new EditForm(this ,true,pouzivatel);
            editForm.setVisible(true);
            
    }//GEN-LAST:event_UpravitButton1ActionPerformed

    private void ZaznamyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZaznamyButtonActionPerformed
       ZaznamyForm zaznamyForm = new ZaznamyForm(this,true,pouzivatel);
           zaznamyForm.setVisible(true);
    }//GEN-LAST:event_ZaznamyButtonActionPerformed

    private void LekáriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LekáriButtonActionPerformed
        LekarForm lekarForm = new LekarForm(this, true);
           lekarForm.setVisible(true);
    }//GEN-LAST:event_LekáriButtonActionPerformed

    private void PacientiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacientiButtonActionPerformed
         PacientForm pacientForm = new PacientForm(this, true);
           pacientForm.setVisible(true);
    }//GEN-LAST:event_PacientiButtonActionPerformed

    private void DatabazaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabazaButtonActionPerformed
          DatabazaForm databazaForm = new DatabazaForm(this, true);
           databazaForm.setVisible(true); 
    }//GEN-LAST:event_DatabazaButtonActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DatabazaButton;
    private javax.swing.JLabel DatabazaLabel;
    private javax.swing.JButton LekáriButton;
    private javax.swing.JLabel LekáriLabel;
    private javax.swing.JButton OdhalsitButton;
    private javax.swing.JButton PacientiButton;
    private javax.swing.JLabel PacientiLabel;
    private javax.swing.JButton UpravitButton1;
    private javax.swing.JButton ZaznamyButton;
    private javax.swing.JLabel ZaznamyLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
